[project]
name = "fitting-curvature"
version = "0.1.0"
description = "Learn the curvature of your data and fit an embedding into it."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "tqdm>=4.67.1",
]
